apiVersion: v1
kind: Secret
metadata:
  name: exam-client-jwt
  namespace: kafka
  labels:
    konghq.com/credential: jwt    # Label fondamentale per il discovery di Kong
stringData:
  key: "exam-client-key"  #valore che useremo come iss nel token;
  secret: "supersecret"   #chiave condivisa per firmare/verificare il token
  algorithm: "HS256"

