apiVersion: v1
kind: Secret
metadata:
  name: exam-client-jwt
  namespace: kafka
  labels:
    konghq.com/credential: jwt    # Label fondamentale per il discovery di Kong
stringData:
  congig: | #KEY: valore che useremo come iss nel token; secret â†’ chiave condivisa per firmare/verificare il token
    {
      "key": "exam-client-key",   
      "secret": "supersecret",
      "algorithm": "HS256"
    }
  konsumerRef: exam-client

