apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: student-events
  namespace: kafka
  labels:
    strimzi.io/cluster: uni-it-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000   # 7 giorni
    segment.bytes: 1073741824 # 1GB per segment