# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: metrics-ingress
#   namespace: metrics
#   annotations:
#     #konghq.com/strip-path: "true"
# spec:
#   ingressClassName: kong
#   rules:
#     - host: metrics.local
#       http:
#         paths:
#           - path: /metrics
#             pathType: Prefix
#             backend:
#               service:
#                 name: metrics-service
#                 port:
#                   number: 5001


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-ingress
  namespace: metrics
  annotations:
    konghq.com/plugins: jwt-auth  #ABILITA AUTENTICAZIONE CON JWT
    #konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - host: metrics.192.168.49.2.nip.io
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: metrics-service
                port:
                  number: 5001