apiVersion: v1
kind: Secret
metadata:
  name: iot-devices-apikey
  namespace: kafka
  labels:
    konghq.com/credential: key-auth
stringData:
  key: "iot-sensor-key-prod-v1"
  # In produzione: generare con `openssl rand -hex 32`