apiVersion: v1
kind: Secret
metadata:
  name: iot-devices-apikey
  namespace: kafka
  labels:
    # questo Secret contiene credenziali per il plugin 'key-auth'.
    konghq.com/credential: key-auth
stringData:
  # La chiave effettiva che i client devono inviare.
  # NOTA: Usiamo 'stringData' per leggibilità qui, ma K8s la convertirà in base64.
  key: "iot-sensor-key-prod-v1"
  # In produzione: generare con `openssl rand -hex 32`