apiVersion: v1
kind: Secret
metadata:
  name: iot-devices-apikey
  # Duplichiamo il secret nel namespace 'metrics' perché i Secret non sono condivisibili tra namespace.
  namespace: metrics
  labels:
    konghq.com/credential: key-auth
stringData:
  # Stessa chiave per uniformità lato client
  key: "iot-sensor-key-prod-v1"